#ifndef _DEFAULT_CREATE_INFO_H
#define _DEFAULT_CREATE_INFO_H
#include <vulkan/vulkan.h>

const VkBufferCreateInfo VK_DEFAULT_BUFFER_CREATE_INFO = {
	VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
	nullptr,
	NULL,
	NULL,
	NULL,
	VK_SHARING_MODE_EXCLUSIVE,
	NULL,
	nullptr
};

const VkPipelineColorBlendAttachmentState VK_DEFAULT_COLOR_BLEND_ATTACHMENT_STATE = {
	VK_TRUE,
	VK_BLEND_FACTOR_SRC_ALPHA,
	VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
	VK_BLEND_OP_ADD,
	VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
	VK_BLEND_FACTOR_ZERO,
	VK_BLEND_OP_ADD,
	VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT
};
#endif